-- GTM Tracking Platform - Enhanced Data Models
-- Adds columns for richer browser, website, and user data

-- ── Users: enrich profile & account data ──
ALTER TABLE users ADD COLUMN IF NOT EXISTS company VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(100) NOT NULL DEFAULT 'UTC';
ALTER TABLE users ADD COLUMN IF NOT EXISTS locale VARCHAR(20) NOT NULL DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_settings JSONB NOT NULL DEFAULT '{}';

ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(50) NOT NULL DEFAULT 'free';
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS events_this_month INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS events_limit INTEGER NOT NULL DEFAULT 100000;

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- ── Websites: enrich tracking config & compliance ──
ALTER TABLE websites ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE websites ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'active';

ALTER TABLE websites ADD COLUMN IF NOT EXISTS meta_test_event_code VARCHAR(255);

ALTER TABLE websites ADD COLUMN IF NOT EXISTS auto_track_pageview BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS auto_track_click BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS auto_track_scroll BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS auto_track_form BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS cookie_domain VARCHAR(255);

ALTER TABLE websites ADD COLUMN IF NOT EXISTS gdpr_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS consent_mode VARCHAR(50) NOT NULL DEFAULT 'default';
ALTER TABLE websites ADD COLUMN IF NOT EXISTS data_retention_days INTEGER NOT NULL DEFAULT 365;

ALTER TABLE websites ADD COLUMN IF NOT EXISTS domain_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS verification_token VARCHAR(255);
ALTER TABLE websites ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE websites ADD COLUMN IF NOT EXISTS favicon TEXT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7);

ALTER TABLE websites ADD COLUMN IF NOT EXISTS timezone VARCHAR(100) NOT NULL DEFAULT 'UTC';
ALTER TABLE websites ADD COLUMN IF NOT EXISTS script_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS allowed_origins TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE websites ADD COLUMN IF NOT EXISTS last_event_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- ── Events: structured context columns ──
ALTER TABLE events ADD COLUMN IF NOT EXISTS device_info JSONB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS page_info JSONB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS performance_info JSONB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS network_info JSONB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS location_info JSONB;

ALTER TABLE events ADD COLUMN IF NOT EXISTS properties JSONB NOT NULL DEFAULT '{}';

ALTER TABLE events ALTER COLUMN payload DROP NOT NULL;
ALTER TABLE events ALTER COLUMN payload SET DEFAULT NULL;

-- ── Sessions: enrich with device & location ──
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS device_info JSONB;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS location_info JSONB;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS utm_term VARCHAR(255);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS utm_content VARCHAR(255);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS landing_page TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS exit_page TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS page_views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS duration_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS browser_timezone VARCHAR(100);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- ── Visitor profiles table (persistent identity) ──
CREATE TABLE IF NOT EXISTS visitor_profiles (
    visitor_id VARCHAR(255) PRIMARY KEY,
    first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    email VARCHAR(255),
    phone VARCHAR(50),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    zip VARCHAR(20),
    birth_date VARCHAR(20),
    gender VARCHAR(50),
    custom_data JSONB DEFAULT '{}',
    device_info JSONB,
    location_info JSONB,
    total_sessions INTEGER NOT NULL DEFAULT 0,
    total_events INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_visitor_profiles_email ON visitor_profiles(email);
CREATE INDEX IF NOT EXISTS idx_visitor_profiles_last_seen ON visitor_profiles(last_seen_at);
